kind: pipeline
name: default

steps:
#Build Way 1
- name: build
  image: node:9.8.0
  pull: if-not-exists
  commands:
  - npm install
  - npm test

#Build Way 2
# - name: build
#   image: node:9.8.0
#   pull: if-not-exists
#   commands:
#   - sh ./.drone/build.sh

- name: publish
  image: plugins/docker:latest
  pull: if-not-exists
  settings:
    repo: nishanthkp/node-microservice
    tags: ["build_${DRONE_BUILD_NUMBER}", "latest"]
    when:
      branch: master
      event: commit
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD 

- name: deploy
  image: widerin/openshift-cli
  pull: if-not-exists
  commands:
  - oc login --token=$OPENSHIFT_TOKEN --server=$OPENSHIFT_SERVER
  - oc project danske-training
  - oc new-app nishanthkp/node-microservice:latest --name=node-microservice-nishanth

